### ISSUE TITLE
[Bug] "Could not refresh. Please try again" Stories won't load

### ISSUE THREAD

**Issue by TheNightRider12** [eni9889/SC-PP-ISSUES#111]
iOS: 9.3.5
Jailbreak (also happens on non JB with latest sideload commits)
App Version: 10.21.1
Tweak: 1.7r-2

When loading up snapchat, I get on the top "Could not refresh. Please try again". Chats will load and work perfectly fine. The only thing that doesn't load is stories. No stories show up even though I do follow people and they are always posting to their story.

**Comment by uhhmaybe** [comment]
I mentioned this elsewhere, but if you downgrade to your release of `Snapchat.v10.17.6_v1.6r-168.Duplicate.of.App.Store.App.ipa` you don't get the refresh error with Stories.

Now, correct me if I'm wrong, but wasn't that the release where you changed how you were making the IPAs?  See this post here on reddit where I say that the refreshing Stories error is fixed and you say you changed the Bundle ID:

https://www.reddit.com/r/iPAHub/comments/6q8eo2/update_ipa_repo_post/dnkdot0/

So maybe the fix for the refresh error on Stories is related to that, and you just have to remake the newer release with a new Bundle ID again.
