### ISSUE TITLE
(Jailbreak) Adding and removing or blocking friends doesn’t work

### ISSUE THREAD

**Issue by justin0386** [eni9889/SC-PP-ISSUES#203]
iOS Version 11.1.2
 Snapchat Version latest
 SC ++ Tweak Version latest
 Crash Report: no crash
 Please label the issue either Jailbreak or Sideloaded

**Comment by eni9889** [comment]
Can you please provide more details? blocking from where?

**Comment by justin0386** [comment]
Every time i try to remove someone from snapchat it keeps saying could not remove friend. It also says could not refresh please try again. Saving and sending snaps and stories works. I just cant remove, accept, or block ppl from my snapchat.

**Comment by mrwavesurf22** [comment]
@eni9889 do you know where can I download the ipa for the latest version please? I could not find on JMccormick264's repo page or on beta.unlimapps.com

**Comment by eni9889** [comment]
Is this on sideloaded or jailbreak?

**Comment by justin0386** [comment]
@eni9889 its on jailbreak. An its not on sideloaded. My sideloaded duplicate works just fine..

**Comment by mrwavesurf22** [comment]
@eni9889 On sideloaded

**Comment by lordcatalien** [comment]
Since upgrading to Snapchat.v10.27.1.1_v1.7r-54 I've gotten the same issue. When I click my bitmoji to go to the settings screen, I see a "Could Not Refresh. Please Try Again" grey bar at the top of the screen. Then, when I click "Add Friends," I can search by username, but clicking the little ( + ) next to their name makes the plus temporarily disappear but it comes back a moment later and the friend isn't added (or pending). I've tried with a number of friends, but same result.

**Comment by justin0386** [comment]
What i also have noticed is that it also does it without any snapchat related tweaks installed even just being in jailbreak mode does it. Non jailbroken mode it works fine though.
