### ISSUE TITLE
[BUG] Snapchat crashes when saving edits to an existing group

### ISSUE THREAD

**Issue by Kosmooo** [eni9889/SC-PP-ISSUES#42]
iOS Version: 10.0.1
Snapchat Version: 10.14.1.0
SC ++ Tweak Version: 1.6r-149
Jailbroken

**Comment by ghost** [comment]
I opened a thread (#37) because this happened to me with a mute list. I believe it happened because some people from the group were deleted from my snapchat. A temporary option I did was remove the tweak, delete the app, and use iCleaner. Then I reinstalled the tweak and app and it was back to default settings and I can now edit my groups/mute list
